exercise-eqvbintrees
nkoblai/goexercises pull request #10
Opened 2017-06-09 10:22 UTC by nkoblai

2017-06-09 13:46 UTC, arbrix commented on go-tour/eqvbintrees.go
> +	if t1 != nil && t2 != nil {
this check work only for the first value in a tree not to the rest

2017-06-09 13:59 UTC, arbrix commented on go-tour/eqvbintrees.go
> +		if v1 == v2 && ok1 == ok2 {
do you really need this `if`?

2017-06-09 14:02 UTC, arbrix commented on go-tour/eqvbintrees.go
> +	if t != nil {
in golang usually use another approach: returns or small logic by condition and other logic is placed after that for improving readability

2017-06-09 14:02 UTC, arbrix requested changes
small changes required

2017-06-12 13:05 UTC, nkoblai commented
@arbrix fixed

2017-06-13 08:53 UTC, arbrix approved these changes
LGTM

2017-06-13 12:35 UTC, merged