'exercise-stringer'
nkoblai/goexercises pull request #5
Opened 2017-06-07 09:13 UTC by nkoblai

2017-06-07 10:36 UTC, arbrix requested changes

2017-06-07 10:36 UTC, arbrix commented on go-tour/stringer.go
> +		fmt.Printf("%v: %v\n", name, ip)
why do you use `%v` instead of `%s`

2017-06-07 10:36 UTC, arbrix commented on go-tour/stringer.go
> +func (ip IPAddr) String() string {
Exported function, comment is missing;
Try to find more simple solution;

2017-06-08 14:19 UTC, nkoblai commented on go-tour/stringer.go
> +		fmt.Printf("%v: %v\n", name, ip)
fixed

2017-06-09 14:12 UTC, nkoblai commented
@arbrix fixed

2017-06-13 08:51 UTC, arbrix commented on go-tour/stringer.go
> +		fmt.Printf("%v: %v\n", name, ip)
make a benchmark for comparing your implementation with another one with strconv package, please

2017-06-21 16:13 UTC, arbrix requested changes
change benchmark

2017-06-21 16:13 UTC, arbrix commented on go-tour/stringer_test.go
> +		for _, ip := range hosts {
this will cause additional costs for iteration, benchmark don't care about the result - it more about performance

2017-06-22 14:20 UTC, arbrix approved these changes
LGTM

2017-06-23 14:18 UTC, merged