exercise-errors
nkoblai/goexercises pull request #6
Opened 2017-06-07 13:33 UTC by nkoblai

2017-06-08 11:40 UTC, arbrix requested changes

2017-06-08 11:40 UTC, arbrix commented on go-tour/errors.go
> +	} else {
`else` unnecessary in this case

2017-06-08 11:40 UTC, arbrix commented on go-tour/errors.go
> +	f, err := Sqrt(1)
only one case, add more to validate error case

2017-06-08 14:16 UTC, nkoblai commented on go-tour/errors.go
> +	} else {
added one more case

2017-06-08 14:22 UTC, nkoblai commented on go-tour/errors.go
> +	f, err := Sqrt(1)
added one more case

2017-06-09 14:11 UTC, nkoblai commented
@arbrix fixed

2017-06-21 16:16 UTC, arbrix approved these changes
LGTM, try to use table tests in the future

2017-06-22 07:33 UTC, merged